name: CI

on:
  push:
  pull_request:

jobs:
  run_tests:
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
        python-version:
          - "3.9"

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas
          python -m pip install -r requirements.txt

      - name: Run unit tests
        run: pytest
